### PR TITLE
add tutorials

### PR DESCRIPTION
**Pull request by jamiltz**
Merging tutorials from https://github.com/couchbaselabs/couchbase-by-example to have everything in one place.

### CODE REVIEW

**Comment by tleyden** [comment]
@jamiltz you should assign the PR to someone

**Comment by hideki** [comment]
This PR has 146 file changes. Honestly it is hard to review.

**Comment by jamiltz** [comment]
Ah yes, I should have mentioned that the content was already reviewed. This PR is to merge another repo into this one. So what needs to be reviewed is wether the file structure in this PR makes sense. Sorry for the confusion. I'll assign @zgramana as we chatted over skype about it already.

**Comment by zgramana** [comment]
@jamiltz I'll review this today.

**Comment by zgramana** [comment]
@jamiltz could you please remove the numeric prefix from the migrated folder paths?

**Pull request merged**
